---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-lighthouse-agent
subjects:
  - kind: ServiceAccount
    name: submariner-lighthouse-agent
    namespace: $(SA_NAMESPACE)
roleRef:
  kind: ClusterRole
  name: submariner-lighthouse-agent
  apiGroup: rbac.authorization.k8s.io
