---
resources:
  - submariner-operator/service_account.yaml
  - submariner-operator/role.yaml
  - submariner-operator/role_binding.yaml
  - submariner-operator/cluster_role.yaml
  - submariner-operator/cluster_role_binding.yaml
  - submariner-gateway/service_account.yaml
  - submariner-gateway/role.yaml
  - submariner-gateway/role_binding.yaml
  - submariner-route-agent/service_account.yaml
  - submariner-route-agent/role.yaml
  - submariner-route-agent/role_binding.yaml
  - submariner-route-agent/cluster_role.yaml
  - submariner-route-agent/cluster_role_binding.yaml
  - submariner-globalnet/service_account.yaml
  - submariner-globalnet/role.yaml
  - submariner-globalnet/role_binding.yaml
  - submariner-globalnet/cluster_role.yaml
  - submariner-globalnet/cluster_role_binding.yaml
  - lighthouse-agent/service_account.yaml
  - lighthouse-agent/cluster_role.yaml
  - lighthouse-agent/cluster_role_binding.yaml
  - lighthouse-coredns/service_account.yaml
  - lighthouse-coredns/cluster_role.yaml
  - lighthouse-coredns/cluster_role_binding.yaml
  - networkplugin_syncer/service_account.yaml
  - networkplugin_syncer/cluster_role.yaml
  - networkplugin_syncer/cluster_role_binding.yaml
# - leader_election/leader_election_role.yaml
# - leader_election/leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
# - auth_proxy/auth_proxy_service.yaml
# - auth_proxy/auth_proxy_role.yaml
# - auth_proxy/auth_proxy_role_binding.yaml
# - auth_proxy/auth_proxy_client_clusterrole.yaml
