---
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
spec:
  components:
    - service-discovery
    - connectivity
  defaultGlobalnetClusterSize: 8192
  globalnetEnabled: false
  # globalnetCIDRRange: 169.254.0.0/16
  #  defaultCustomDomains:
