---
apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
  name: example-submariner
spec:
  namespace: "submariner-operator"
  serviceCIDR: "192.168.66.0/24"
  clusterCIDR: "192.168.67.0/24"
  globalCIDR: "169.254.0.0/16"
  clusterID: "east"
  colorCodes: "blue"
  debug: false
  natEnabled: true
  serviceDiscoveryEnabled: true
  broker: "k8s"
  brokerK8sApiServer: "192.168.67.110:8443"
  brokerK8sApiServerToken: "$(SECRET_API_SERVER_TOKEN)"
  brokerK8sRemoteNamespace: "submariner-broker"
  brokerK8sCA: "$(SECRET_CA)"
  cableDriver: "libreswan"
  ceIPSecPSK: "$(SECRET_IPSEC_PSK)"
  ceIPSecDebug: false
  ceIPSecIKEPort: 500
  ceIPSecNATTPort: 4500
  repository: "quay.io/submariner"
  version: "$(VERSION)"
