---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - path: patches/brokers.crd.config.yaml
    target:
      group: operators.coreos.com
      kind: ClusterServiceVersion
      name: submariner.v${VERSION}
      namespace: placeholder
      version: v1alpha1
  - path: patches/submariners.crd.config.yaml
    target:
      group: operators.coreos.com
      kind: ClusterServiceVersion
      name: submariner.v${VERSION}
      namespace: placeholder
      version: v1alpha1
# - path: patches/servicediscoveries.crd.config.yaml
#  target:
#    group: operators.coreos.com
#    kind: ClusterServiceVersion
#    name: submariner.v*
#    namespace: placeholder
#    version: v1alpha1
vars:
  - fieldref:
      fieldpath: spec.version
    name: VERSION
    objref:
      group: operators.coreos.com
      kind: ClusterServiceVersion
      name: submariner.v${VERSION}
      version: v1alpha1
commonAnnotations:
  createdAt: null
