apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- ../samples
- ../scorecard

images:
- name: controller
  newName: quay.io/submariner/submariner-operator
  newTag: 0.10.0
- name: repo
  newName: quay.io/submariner
