---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.1
  name: brokers.submariner.io
spec:
  group: submariner.io
  names:
    kind: Broker
    listKind: BrokerList
    plural: brokers
    singular: broker
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Broker is the Schema for the brokers API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BrokerSpec defines the desired state of Broker.
            properties:
              clustersetIPCIDRRange:
                description: ClustersetIP supernet range for allocating ClustersetIPCIDRs
                  to each cluster.
                type: string
              components:
                description: List of the components to be installed - any of [service-discovery,
                  connectivity].
                items:
                  type: string
                type: array
              defaultCustomDomains:
                description: List of domains to use for multi-cluster service discovery.
                items:
                  type: string
                type: array
              defaultGlobalnetClusterSize:
                description: Default cluster size for GlobalCIDR allocated to each
                  cluster (amount of global IPs).
                type: integer
              globalnetCIDRRange:
                description: GlobalCIDR supernet range for allocating GlobalCIDRs
                  to each cluster.
                type: string
              globalnetEnabled:
                description: Enable support for Overlapping CIDRs in connecting clusters.
                type: boolean
              clustersetIPEnabled:
                description: Enable ClustersetIP default for connecting clusters.
                type: boolean
            type: object
          status:
            description: BrokerStatus defines the observed state of Broker.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
