---
name: End to End Default

on:
  pull_request:

jobs:
  e2e:
    name: new_subctl
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: make old subctl
        run: |
          make bin/subctl

      - name: make new subctl
        run: |
          make cmd/bin/subctl

      - name: show subctl help
        run: |
          cmd/bin/subctl help
          cmd/bin/subctl deploy-broker --help
          cmd/bin/subctl join --help

      - name: Deploy clusters
        run: |
          make clusters

      - name: Deploy broker
        run: |
          cmd/bin/subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --broker-namespace newnamespace

      - name: Label gateway nodes
        run: |
          kubectl --kubeconfig output/kubeconfigs/kind-config-cluster1 label node cluster1-worker submariner.io/gateway=true --overwrite
          kubectl --kubeconfig output/kubeconfigs/kind-config-cluster2 label node cluster2-worker submariner.io/gateway=true --overwrite

      - name: Join clusters
        run: |
          cmd/bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1 broker-info.subm --clusterid cluster1 --natt=false \
            --servicecidr 100.1.0.0/16 --clustercidr 10.1.0.0/16
          cmd/bin/subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --natt=false \
            --servicecidr 100.2.0.0/16 --clustercidr 10.2.0.0/16

      - name: Test benchmark
        run: |
          cmd/bin/subctl benchmark latency --kubeconfig output/kubeconfigs/kind-config-cluster1:output/kubeconfigs/kind-config-cluster2 \
          	--kubecontexts cluster1,cluster2 --verbose
          cmd/bin/subctl benchmark latency --kubeconfig output/kubeconfigs/kind-config-cluster1 --kubecontexts cluster1 --intra-cluster
          cmd/bin/subctl benchmark throughput --kubeconfig output/kubeconfigs/kind-config-cluster1:output/kubeconfigs/kind-config-cluster2 \
          	--kubecontexts cluster1,cluster2
          cmd/bin/subctl benchmark throughput --kubeconfig output/kubeconfigs/kind-config-cluster1 --kubecontexts cluster1 \
            --intra-cluster --verbose


      - name: Test verify
        run: |
          cmd/bin/subctl verify --only connectivity --submariner-namespace=submariner-operator --verbose --connection-timeout 20 \
            --connection-attempts 4 --kubeconfig output/kubeconfigs/kind-config-cluster1:output/kubeconfigs/kind-config-cluster2 \
            --kubecontexts cluster1,cluster2

      - name: Test diagnose
        run: |
          cmd/bin/subctl diagnose all --kubeconfig output/kubeconfigs/kind-config-cluster1
          cmd/bin/subctl diagnose firewall inter-cluster output/kubeconfigs/kind-config-cluster1 output/kubeconfigs/kind-config-cluster2

      - name: Test show
        run: |
          cmd/bin/subctl show all --kubeconfig output/kubeconfigs/kind-config-cluster1
