---
name: End to End Default

on:
  pull_request:

jobs:
  e2e:
    name: new_subctl
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Deploy clusters
        run: |
          make clusters

      - name: Generate embeddedyamls
        run: |
          make generate-embeddedyamls

      - name: make new subctl
        run: |
          cd cmd
          make bin/subctl

      - name: show subctl help
        run: |
          subctl --help
          subctl deploy-broker --help

      - name: Deploy broker
        run: |
          subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1
