---
name: End to End Default

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, converted_to_draft, labeled]

permissions: {}

jobs:
  e2e:
    name: E2E
    if: github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test-draft')
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.15

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.15
