on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: End to End Tests
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        lighthouse: ['', 'lighthouse']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        run: |
          make e2e using="${{ matrix.globalnet }} ${{ matrix.lighthouse }}"

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
  olm:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment using OLM and tests
        run: |
          make e2e using="olm"

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
