---
name: End to End Tests

on:
  pull_request:

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        k8s_version: ['1.20.2']
        lighthouse: ['', 'lighthouse']
        ovn: ['', 'ovn']
        exclude:
          - ovn: 'ovn'
            lighthouse: 'lighthouse'
          - ovn: 'ovn'
            globalnet: 'globalnet'
        include:
          # This is the oldest K8s version we try to support
          - k8s_version: 1.17.17
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.9
        with:
          k8s_version: ${{ matrix.k8s_version }}
          using: ${{ matrix.globalnet }} ${{ matrix.lighthouse }} ${{ matrix.ovn }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.9
