---
name: Flake Finder

on:
  schedule:
    - cron: "0 0,1 * * *"

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cable_driver: ['libreswan', 'strongswan', 'wireguard']
        globalnet: ['', 'globalnet']
        lighthouse: ['', 'lighthouse']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Reclaim free space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        run: |
          make e2e using="${{ matrix.cable_driver }} ${{ matrix.globalnet }} ${{ matrix.lighthouse }}"

      - name: Post mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem

      - name: Raise an issue to report flaky test failure
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Flaky Failure make e2e using="${{ matrix.cable_driver }} ${{ matrix.globalnet }} ${{ matrix.lighthouse }}"
          content-filepath: .github/ISSUE_TEMPLATE/flaky_failure_automated.md
          labels: automated, flaky failure
