---
name: Flake Finder

on:
  schedule:
    - cron: "0 0,1 * * *"

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cable_driver: ['libreswan', 'wireguard']
        globalnet: ['', 'globalnet']
        k8s_version: ['1.17.17']
        lighthouse: ['', 'lighthouse']
        include:
          # Recentness of K8s versions are limited by kindest/node image releases
          - k8s_version: 1.18.15
          - k8s_version: 1.18.15
            globalnet: 'globalnet'
          - k8s_version: 1.19.7
          - k8s_version: 1.19.7
            globalnet: 'globalnet'
          - k8s_version: 1.20.2
          - k8s_version: 1.20.2
            globalnet: 'globalnet'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.9
        with:
          k8s_version: ${{ matrix.k8s_version }}
          using: ${{ matrix.cable_driver }} ${{ matrix.globalnet }} ${{ matrix.lighthouse }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.9
  upgrade-e2e:
    name: Latest Release to Latest Version
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install an old cluster, upgrade it and check it
        uses: submariner-io/shipyard/gh-actions/upgrade-e2e@release-0.9

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.9
