---
name: Markdown Linting
on: pull_request

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Linting
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          ignore_files: "vendor/*"
