---
name: Periodic

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  markdown-link-check-periodic:
    name: Markdown Links (all files)
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@9710f0fec812ce0a3b98bef4c9d842fc1f39d976
        with:
          config-file: ".markdownlinkcheck.json"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@97e6f902a416aac38834e23fa52e166aad0437d2
        with:
          title: Broken link detected by CI
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link

  test-bundle-periodic:
    name: Operator Bundle Test
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Setup kernel, increase the inotify settings
        run: sudo sysctl -w fs.inotify.max_user_watches=524288 fs.inotify.max_user_instances=512

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Run E2E using the bundle deployment method
        run: |
          make e2e using=olm REPO=localhost:5000 IMG=localhost:5000/submariner-operator:local

      - name: Raise an Issue to report broken bundle
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Broken bundle detected by CI
          content-filepath: .github/ISSUE_TEMPLATE/broken-bundle.md
          labels: automated, broken bundle
