---
name: Release Subctl Devel

on:
  push:
    branches:
      - devel
      - release-*

jobs:
  release-subctl-devel:
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate subctl version
        run: |
          echo "SUBCTL_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "RELEASE=release-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate the subctl release artifacts
        run: make build-cross VERSION=${{ env.SUBCTL_TAG }}

      - name: Install GH CLI
        run: |
          curl -sLo /tmp/gh.deb https://github.com/cli/cli/releases/download/v1.11.0/gh_1.11.0_linux_amd64.deb
          sudo dpkg -i /tmp/gh.deb

      - name: Delete old release
        run: git push -d origin ${{ env.RELEASE }} || true

      - name: Create the release with the updated artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.RELEASE }} dist/*.tar.xz --prerelease \
            --title "Cutting Edge: ${{ env.SUBCTL_TAG }}" \
            --target ${GITHUB_SHA}
