---
name: Release Subctl Devel

on:
  push:
    branches:
      - devel
      - release-*

jobs:
  release-subctl-devel:
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Generate subctl version
        run: echo "SUBCTL_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate the subctl release artifacts
        run: |
          make build-cross VERSION=${{ env.SUBCTL_TAG }}
          echo "BINARIES=$(find dist/ -type f -name '*.tar.xz' -printf '%p ')" >> $GITHUB_ENV

      - name: Update the subctl devel GitHub release with the built artifacts
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: "Cutting Edge: ${{ env.SUBCTL_TAG }}"
          tag: subctl-${{ env.SUBCTL_TAG }}
          files: ${{ env.BINARIES }}

      - name: Update the subctl-devel git tag to point to the released commit
        uses: richardsimko/update-tag@v1.0.5
        with:
          tag_name: subctl-${{ env.SUBCTL_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
