---
name: Consuming Projects

on:
  pull_request:

permissions: {}

jobs:
  unit-testing:
    name: Check subctl
    runs-on: ubuntu-latest
    steps:
      - name: Check out the submariner-operator repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: submariner-operator

      - name: Check out the subctl repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: submariner-io/subctl
          path: subctl
          ref: ${{ github.base_ref }}

      - name: Check out the shipyard repository
        # This is required so that we can run a build involving multiple
        # repositories (using LOCAL_BUILD=1)
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: submariner-io/shipyard
          path: shipyard
          ref: ${{ github.base_ref }}

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: '1.19'
          check-latest: true

      - name: Update the subctl build to use the current submariner-operator
        run: |
          cd subctl
          go mod edit -replace=github.com/submariner-io/submariner-operator=../submariner-operator
          go mod tidy

      - name: Run Go subctl unit tests
        run: make -C subctl LOCAL_BUILD=1 unit
