---
name: Upgrade

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, converted_to_draft, labeled]

jobs:
  upgrade-e2e:
    name: Latest Release to Latest Version
    if: github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test-draft')
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Install an old cluster, upgrade it and check it
        uses: submariner-io/shipyard/gh-actions/upgrade-e2e@feature-multi-active-gw

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@feature-multi-active-gw
