on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: Validations
jobs:
  validate:
    name: Validating
    strategy:
      fail-fast: false
      matrix:
        command: ['test', 'validate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: make generate-embeddedyamls ${{ matrix.command }}
